# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-18 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0002_auto_20170518_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_short',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
