# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-18 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0003_auto_20170518_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='non',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='nos',
            field=models.IntegerField(null=True),
        ),
    ]
