# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-08 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0004_auto_20170508_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='title2',
        ),
    ]
