# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-10 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0005_remove_subject_title2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchname', models.CharField(max_length=100, null=True)),
                ('included_subjects', models.ManyToManyField(to='noteapp.Subject')),
            ],
        ),
    ]
