# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-23 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0005_note_abbr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='srcfile',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
